apiVersion: v1
kind: Service
metadata:
  name: java-test-app-service
  labels:
    app: java-test-app
spec:
  selector:
    app: java-test-app
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    name: http
  type: {{ .Values.serviceType }}