# Default values for testappcaller
appName: testappcaller
image: appmonitoring.azurecr.io/nodejs-caller-app:latest

# Target applications (customize these for your environment)
javaHost: "java-test-app-service.test-ns.svc.cluster.local"
nodejsHost: "nodejs-test-app-service.test-ns.svc.cluster.local" 
pythonHost: "python-test-app-service.test-ns.svc.cluster.local"
dotnetHost: "dotnet-test-app-service.test-ns.svc.cluster.local"
goHost: "go-instrumented-test-app-service.test-ns.svc.cluster.local"

# How often to call targets (in milliseconds)
intervalMs: 5000