apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-caller-app
  namespace: default
  labels:
    app: nodejs-caller-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-caller-app
  template:
    metadata:
      labels:
        app: nodejs-caller-app
    spec:
      containers:
      - name: nodejs-caller-app
        image: appmonitoring.azurecr.io/test-caller-app:latest
        imagePullPolicy: Always
        env:
        - name: TARGET_SERVICE_HOST
          value: "test-app-nodejs-service.test-ns.svc.cluster.local"
        - name: TARGET_SERVICE_PORT
          value: "8080"
        - name: CALL_INTERVAL_MS
          value: "10000"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-caller-app-service
  namespace: default
  labels:
    app: nodejs-caller-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: nodejs-caller-app