---
kind: ConfigMap
apiVersion: v1
data:
  CLUSTER_RESOURCE_ID: "{{ .Values.OmsAgent.aksResourceID }}"
metadata:
  name: container-azm-ms-aks-k8scluster
  namespace: kube-system
  labels:
{{- if .Values.legacyAddonDelivery }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
