



apiVersion: v1
kind: Secret
metadata:
  name: ama-logs-secret
  namespace: kube-system
  labels:
{{- if .Values.legacyAddonDelivery }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
type: Opaque
data:
  WSID: {{ .Values.OmsAgent.workspaceID | b64enc | quote }}
  KEY: {{ .Values.OmsAgent.workspaceKey | b64enc | quote }}
{{- if .Values.OmsAgent.isMoonCake }}
  DOMAIN: {{ b64enc "opinsights.azure.cn" }}
{{- end }}
{{- if .Values.OmsAgent.isFairfax }}
  DOMAIN: {{ b64enc "opinsights.azure.us" }}
{{- end }}
{{- if eq (upper .Values.global.commonGlobals.CloudEnvironment) "USNAT" }}
  DOMAIN: {{ b64enc "opinsights.azure.eaglex.ic.gov" }}
{{- end }}
{{- if eq (upper .Values.global.commonGlobals.CloudEnvironment) "USSEC" }}
  DOMAIN: {{ b64enc "opinsights.azure.microsoft.scloud" }}
{{- end }}
{{- if eq (upper .Values.global.commonGlobals.CloudEnvironment) "AZUREBLEUCLOUD" }}
  DOMAIN: {{ b64enc "opinsights.sovcloud-api.fr" }}
{{- end }}
{{- if .Values.OmsAgent.httpsProxy }}
  PROXY: {{ .Values.OmsAgent.httpsProxy | b64enc | quote }}
{{- else if .Values.OmsAgent.httpProxy }}
  PROXY: {{ .Values.OmsAgent.httpProxy | b64enc | quote }}
{{- end}}
{{- if .Values.OmsAgent.trustedCA }}
  PROXYCERT.crt: {{ .Values.OmsAgent.trustedCA | quote }}
{{- end}}
