---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ama-logs
  namespace: kube-system
  labels:
{{- if .Values.legacyAddonDelivery }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
