{{- $arcSettings := include "arc-extension-settings" . | fromYaml }}
{{- $isArcExtension := $arcSettings.isArcExtension }}
{{/* Arc has credential validation, AKS always renders */}}
{{- if or (not $isArcExtension) (and $isArcExtension (and (ne .Values.amalogs.secret.key "<your_workspace_key>") (ne .Values.amalogs.secret.wsid "<your_workspace_id>") (or (ne .Values.amalogs.env.clusterName "<your_cluster_name>") (ne .Values.amalogs.env.clusterId "<your_cluster_id>") (ne .Values.Azure.Cluster.ResourceId "<your_cluster_id>")))) }}
{{- $cloudEnv := lower .Values.global.commonGlobals.CloudEnvironment }}
apiVersion: v1
kind: Secret
metadata:
  name: ama-logs-secret
  namespace: kube-system
  labels:
{{- if $isArcExtension }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- else }}
{{- if .Values.legacyAddonDelivery }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
{{- end }}
type: Opaque
data:
{{- if $isArcExtension }}
  WSID: {{ required "A valid workspace id is required!" .Values.amalogs.secret.wsid | b64enc | quote }}
  KEY: {{ required "A valid workspace key is required!" .Values.amalogs.secret.key | b64enc | quote }}
  DOMAIN: {{ .Values.amalogs.domain | b64enc | quote }}
  {{- if and (.Values.Azure.proxySettings.isProxyEnabled) (.Values.Azure.proxySettings.httpsProxy) (not .Values.amalogs.ignoreExtensionProxySettings) }}
  PROXY: {{ .Values.Azure.proxySettings.httpsProxy | b64enc | quote }}
  {{- else if and (.Values.Azure.proxySettings.isProxyEnabled) (.Values.Azure.proxySettings.httpProxy) (not .Values.amalogs.ignoreExtensionProxySettings) }}
  PROXY: {{ .Values.Azure.proxySettings.httpProxy | b64enc | quote }}
  {{- else if ne .Values.amalogs.proxy "<your_proxy_config>" }}
  PROXY: {{ .Values.amalogs.proxy | b64enc | quote }}
  {{- end }}
  {{- if and (or .Values.Azure.proxySettings.isProxyEnabled .Values.Azure.proxySettings.isCustomCert) (.Values.Azure.proxySettings.proxyCert) (not .Values.amalogs.ignoreExtensionProxySettings) }}
  PROXYCERT.crt: {{.Values.Azure.proxySettings.proxyCert | b64enc | quote}}
  {{- end }}
{{- else }}
  WSID: {{ .Values.OmsAgent.workspaceID | b64enc | quote }}
  KEY: {{ .Values.OmsAgent.workspaceKey | b64enc | quote }}
{{- if .Values.OmsAgent.isMoonCake }}
  DOMAIN: {{ b64enc "opinsights.azure.cn" }}
{{- end }}
{{- if .Values.OmsAgent.isFairfax }}
  DOMAIN: {{ b64enc "opinsights.azure.us" }}
{{- end }}
{{- if eq $cloudEnv "usnat" }}
  DOMAIN: {{ b64enc "opinsights.azure.eaglex.ic.gov" }}
{{- end }}
{{- if eq $cloudEnv "ussec" }}
  DOMAIN: {{ b64enc "opinsights.azure.microsoft.scloud" }}
{{- end }}
{{- if eq $cloudEnv "azurebleucloud" }}
  DOMAIN: {{ b64enc "opinsights.sovcloud-api.fr" }}
{{- end }}
{{- if .Values.OmsAgent.httpsProxy }}
  PROXY: {{ .Values.OmsAgent.httpsProxy | b64enc | quote }}
{{- else if .Values.OmsAgent.httpProxy }}
  PROXY: {{ .Values.OmsAgent.httpProxy | b64enc | quote }}
{{- end}}
{{- if .Values.OmsAgent.trustedCA }}
  PROXYCERT.crt: {{ .Values.OmsAgent.trustedCA | quote }}
{{- end}}
{{- end }}
{{- end }}
