---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ama-logs-hpa
  namespace: kube-system
  labels:
{{- if .Values.legacyAddonDelivery }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ama-logs-multitenancy
  minReplicas: {{ .Values.OmsAgent.omsAgentMultitenancyLogsHPAMinReplicas }}
  maxReplicas: {{ .Values.OmsAgent.omsAgentMultitenancyLogsHPAMaxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.OmsAgent.omsAgentMultitenancyHPAAvgCPUUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.OmsAgent.omsAgentMultitenancyHPAAvgMemoryUtilization }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1200
      policies:
      - type: Percent
        value: 5
        periodSeconds: 180
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 5
        periodSeconds: 5
      - type: Percent
        value: 100
        periodSeconds: 5
      selectPolicy: Max
