{{- $arcSettings := include "arc-extension-settings" . | fromYaml }}
{{- $isArcExtension := $arcSettings.isArcExtension }}
{{/* Determine isusingaadauth value */}}
{{- $isusingaadauth := false -}}
{{- if not $isArcExtension -}}
  {{- if hasKey .Values.OmsAgent "isUsingAADAuth" -}}
    {{- $isusingaadauth = .Values.OmsAgent.isUsingAADAuth -}}
  {{- end -}}
{{- end -}}
{{/* Arc has rbac condition, AKS always renders */}}
{{- if or (not $isArcExtension) (and $isArcExtension .Values.amalogs.rbac) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ama-logs
  namespace: kube-system
  labels:
{{- if $isArcExtension }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- else }}
{{- if .Values.legacyAddonDelivery }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
{{- end }}
---
kind: ClusterRole
{{- if $isArcExtension }}
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
{{- end }}
metadata:
  name: ama-logs-reader
  labels:
{{- if $isArcExtension }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- else }}
{{- if .Values.legacyAddonDelivery }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
{{- end }}
rules:
- apiGroups: [""]
  resources: ["pods", "events", "nodes", "nodes/stats", "nodes/metrics", "nodes/spec", "nodes/proxy", "namespaces", "services", "persistentvolumes"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["apps", "extensions", "autoscaling"]
  resources: ["replicasets", "deployments", "horizontalpodautoscalers"]
  verbs: ["list"]
{{- if $isArcExtension }}
- apiGroups: ["clusterconfig.azure.com"]
  resources: ["azureclusteridentityrequests", "azureclusteridentityrequests/status"]
  verbs: ["get", "create", "patch", "list", "update", "delete"]
{{- else }}
{{- if .Values.OmsAgent.isRSVPAEnabled }}
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: [ "ama-logs-rs" ]
  verbs: ["get", "patch"]
{{- end }}
{{- if $isusingaadauth }}
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [{{ .Values.OmsAgent.accessTokenSecretName | quote }}]
  verbs: ["get", "watch"]
{{- end }}
{{- end }}
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
{{- if $isArcExtension }}
#arc k8s extension model grants access as part of the extension msi
#remove this explicit permission once the extension available in public preview
{{- if (empty .Values.Azure.Extension.Name) }}
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["container-insights-clusteridentityrequest-token"]
  verbs: ["get"]
{{- end }}
{{- end }}
---
kind: ClusterRoleBinding
{{- if $isArcExtension }}
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
{{- end }}
metadata:
  name: amalogsclusterrolebinding
  labels:
{{- if $isArcExtension }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- else }}
{{- if .Values.legacyAddonDelivery }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
{{- end }}
subjects:
  - kind: ServiceAccount
    name: ama-logs
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: ama-logs-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
