{{- if eq .Values.Azure.Cluster.Distribution "openshift" }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: ama-logs-rs-scc
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
allowPrivilegedContainer: true
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
requiredDropCapabilities: []
defaultAddCapabilities: []
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- projected
- secret
users:
- system:serviceaccount:kube-system:ama-logs
{{- end }}
