apiVersion: monitor.azure.com/v1 
kind: Instrumentation
metadata:
  name: default
  namespace: test-ns
spec:  
  settings:
    autoInstrumentationPlatforms: # required, could be empty
      - Java
      - NodeJs
  destination: # required
    applicationInsightsConnectionString: InstrumentationKey=0c12a0a6-a10c-4722-8753-0644d2938d45;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=37743a46-5226-447c-842b-35fac54dbd92
