apiVersion: monitor.azure.com/v1 
kind: Instrumentation
metadata:
  name: default
  namespace: ${TEST_NS}
spec:  
  settings:
    autoInstrumentationPlatforms: # required, could be empty
      - Java
      - NodeJs
  destination: # required
    applicationInsightsConnectionString: ${AI_CONNECTION_STRING}
