apiVersion: monitor.azure.com/v1 
kind: Instrumentation
metadata:
  name: default
  namespace: test-ns
spec:  
  settings:
    autoInstrumentationPlatforms: # required, could be empty
      - Java
      - NodeJs
  destination: # required
    applicationInsightsConnectionString: InstrumentationKey=2b453402-fcfb-408f-8495-c551f0e82f46;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=71a68a81-915e-4686-9f4b-eadcfc28689a
