apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 13000
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "{{ .Values.port }}"
            - name: APPLICATIONINSIGHTS_CONFIGURATION_CONTENT
              value: {{ .Values.appInsightsConfig | quote }}
            - name: TARGET_URL
              value: "{{ .Values.targetUrl }}"
          ports:
            - containerPort: {{ .Values.port }}