apiVersion: v1
kind: Service
metadata:
  name: nodejs-test-app-service
  labels:
    app: nodejs-test-app
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
  selector:
    app: nodejs-test-app