{
 "title": "Azure Monitor / Container Insights /QoS - Logs Multitenacy - Advanced Mode",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"cadvisor\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Daemonset (for selected namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Fluent-bit incoming (before throttle) records/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_filter_records_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Fluent-bit dropped (due to throttle) records/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_filter_drop_records_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Fluent-bit input (after throttle)  records/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_input_records_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Fluent-bit output forwarded records/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Fluent-bit incoming (before throttle) records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_filter_records_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit dropped (due to throttle) records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_filter_drop_records_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input (after throttle) records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_records_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output forwarded records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input bytes/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_input_bytes_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Fluent-bit output forwarded bytes/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_output_proc_bytes_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Fluent-bit input  bytes/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_bytes_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output forwarded bytes/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 23 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_proc_bytes_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit retries failed/sec by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "\r\nsum by (node) (rate(fluentbit_output_retries_failed_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\", name=~\"azmon_tenant_${namespace}_.*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output errors/sec by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 29 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_errors_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Daemonset (all namespaces)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Fluent-bit incoming(before throttle) records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_filter_records_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\",name!~\"ama-logs-*|mon-agent-*|telegraf-*|azmon_tenant_record_modifier|azmon_tenant_grep|fluentbit_metrics_input|storage_*|fluentbit_metrics_input|oms_output\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input (after throttle) records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_records_total{cluster=~\"$cluster\", name!~\"ama-logs-*|mon-agent-*|telegraf-*|azmon_tenant_record_modifier|azmon_tenant_grep|fluentbit_metrics_input|storage_*|fluentbit_metrics_input|oms_output\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output (after throttle) records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 36 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\",name!~\"ama-logs-*|mon-agent-*|telegraf-*|azmon_tenant_record_modifier|azmon_tenant_grep|fluentbit_metrics_input|storage_*|fluentbit_metrics_input|oms_output\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit retries failed/sec by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "\r\nsum by (node) (rate(fluentbit_output_retries_failed_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output errors/sec by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 44 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_errors_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\" }[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Service side (for all namespaces)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "Fluent-bit received records/s by Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_input_records_total{cluster=~\"$cluster\", job=\"ama-logs-multitenancy\", instance=~\"ama-logs-multitenancy-.*\", name=\"input_ama-logs-service_forward\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit out forward (to LA) records/s by Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 52 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\", job=\"ama-logs-multitenancy\", instance=~\"ama-logs-multitenancy-*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output errors (to LA) count/s by Instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_errors_total{cluster=~\"$cluster\", job=\"ama-logs-multitenancy\", instance=~\"ama-logs-multitenancy-*\", name=\"output_ama-logs-service_azmon\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output retries failed (to LA) count/s by Instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 59 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_output_retries_failed_total{cluster=~\"$cluster\", job=\"ama-logs-multitenancy\", instance=~\"ama-logs-multitenancy-*\", name=\"output_ama-logs-service_azmon\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}