apiVersion: v1
kind: Service
metadata:
  name: testappsource-service
  labels:
    app: testappsource
spec:
  type: ClusterIP
  selector:
    app: testappsource
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}