apiVersion: apps/v1
kind: Deployment
metadata:
  name: testappsource
  labels:
    app: testappsource
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testappsource
  template:
    metadata:
      labels:
        app: testappsource
    spec:
      containers:
      - name: testappsource
        image: "{{ .Values.image }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: PORT
          value: "{{ .Values.port }}"
        - name: MESSAGE
          value: "{{ .Values.message }}"