apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
      annotations:
        instrumentation.opentelemetry.io/private-preview-inject-python: "true" # private-preview is enabled via an annotation only
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 14000
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          env:
            - name: TARGET_URL
              value: "{{ .Values.targetUrl }}"
          ports:
            - containerPort: {{ .Values.port }}
