{{/* Auto-generated by versioning tooling, do not edit. See /toolkit/versioning/README.md for more information. */}}
{{- define "get.addonImageTag" -}}
  {{- if eq .component "aci-connector-linux" -}}
    {{- if semverCompare ">=1.26.0" .version -}}1.6.2
    {{- else if semverCompare ">=1.25.0" .version -}}1.6.1
    {{- else if semverCompare ">=1.24.0" .version -}}1.6.0
    {{- else -}}1.4.16
    {{- end -}}
  {{- else if eq .component "addon-resizer" -}}
v1.8.23-4
  {{- else if eq .component "ai-toolchain-operator" -}}
0.6.0
  {{- else if eq .component "aks-windows-gpu-device-plugin" -}}
0.0.19
  {{- else if eq .component "ama-logs-linux" -}}
3.1.28
  {{- else if eq .component "ama-logs-win" -}}
win-3.1.28
  {{- else if eq .component "app-routing-operator" -}}
0.0.3
  {{- else if eq .component "azure-monitor-metrics-cfg-reader" -}}
6.21.1-main-08-15-2025-f5f679d6-cfg
  {{- else if eq .component "azure-monitor-metrics-ksm" -}}
v2.15.0-4
  {{- else if eq .component "azure-monitor-metrics-linux" -}}
6.21.1-main-08-15-2025-f5f679d6
  {{- else if eq .component "azure-monitor-metrics-target-allocator" -}}
6.21.1-main-08-15-2025-f5f679d6-targetallocator
  {{- else if eq .component "azure-monitor-metrics-windows" -}}
6.21.1-main-08-15-2025-f5f679d6-win
  {{- else if eq .component "azure-npm-image" -}}
v1.6.33
  {{- else if eq .component "azure-npm-image-windows" -}}
v1.5.5
  {{- else if eq .component "azure-policy" -}}
    {{- if semverCompare ">=1.27.0" .version -}}1.13.0
    {{- else if semverCompare ">=1.25.0" .version -}}1.4.0
    {{- else if semverCompare ">=1.24.0" .version -}}1.0.1
    {{- else if semverCompare ">=1.21.0" .version -}}0.0.3
    {{- else -}}0.0.1
    {{- end -}}
  {{- else if eq .component "azure-policy-webhook" -}}
    {{- if semverCompare ">=1.27.0" .version -}}1.13.0
    {{- else if semverCompare ">=1.25.0" .version -}}1.4.0
    {{- else if semverCompare ">=1.24.0" .version -}}1.0.1
    {{- else if semverCompare ">=1.21.0" .version -}}0.0.3
    {{- else if semverCompare ">=1.18.0" .version -}}0.0.2
    {{- else -}}0.0.1
    {{- end -}}
  {{- else if eq .component "certgen" -}}
v0.1.9
  {{- else if eq .component "cilium-agent" -}}
    {{- if semverCompare ">=1.29.0" .version -}}1.14.10-1
    {{- else if semverCompare ">=1.27.0" .version -}}1.13.13-3
    {{- else -}}1.12.10-5
    {{- end -}}
  {{- else if eq .component "cilium-envoy" -}}
v1.31.5-250218
  {{- else if eq .component "cilium-operator-generic" -}}
    {{- if semverCompare ">=1.29.0" .version -}}1.14.10
    {{- else if semverCompare ">=1.27.0" .version -}}1.13.13
    {{- else -}}1.12.10
    {{- end -}}
  {{- else if eq .component "cloud-provider-node-manager-linux" -}}
    {{- if semverCompare ">=1.33.0" .version -}}v1.33.0
    {{- else if semverCompare ">=1.32.0" .version -}}v1.32.5
    {{- else if semverCompare ">=1.31.0" .version -}}v1.31.6
    {{- else if semverCompare ">=1.30.0" .version -}}v1.30.12
    {{- else if semverCompare ">=1.29.0" .version -}}v1.29.15
    {{- else if semverCompare ">=1.28.0" .version -}}v1.28.14
    {{- else if semverCompare ">=1.27.0" .version -}}v1.27.21
    {{- else if semverCompare ">=1.26.0" .version -}}v1.26.22
    {{- else if semverCompare ">=1.25.0" .version -}}v1.25.24
    {{- else if semverCompare ">=1.24.0" .version -}}v1.24.21
    {{- else if semverCompare ">=1.23.0" .version -}}v1.23.24
    {{- else if semverCompare ">=1.22.0" .version -}}v1.1.14
    {{- else if semverCompare ">=1.21.0" .version -}}v1.0.18
    {{- else if semverCompare ">=1.20.0" .version -}}v0.7.21
    {{- else if semverCompare ">=1.19.0" .version -}}v0.6.0
    {{- else -}}v0.5.1.4
    {{- end -}}
  {{- else if eq .component "cloud-provider-node-manager-windows" -}}
    {{- if semverCompare ">=1.33.0" .version -}}v1.33.0
    {{- else if semverCompare ">=1.32.0" .version -}}v1.32.5
    {{- else if semverCompare ">=1.31.0" .version -}}v1.31.6
    {{- else if semverCompare ">=1.30.0" .version -}}v1.30.12
    {{- else if semverCompare ">=1.29.0" .version -}}v1.29.15
    {{- else if semverCompare ">=1.28.0" .version -}}v1.28.14
    {{- else if semverCompare ">=1.27.0" .version -}}v1.27.21
    {{- else if semverCompare ">=1.26.0" .version -}}v1.26.22
    {{- else if semverCompare ">=1.25.0" .version -}}v1.25.24
    {{- else if semverCompare ">=1.24.0" .version -}}v1.24.21
    {{- else if semverCompare ">=1.23.0" .version -}}v1.23.24
    {{- else if semverCompare ">=1.22.0" .version -}}v1.1.14
    {{- else if semverCompare ">=1.21.0" .version -}}v1.0.18
    {{- else if semverCompare ">=1.20.0" .version -}}v0.7.21
    {{- else if semverCompare ">=1.19.0" .version -}}v0.6.0
    {{- else -}}v0.5.1
    {{- end -}}
  {{- else if eq .component "cluster-proportional-autoscaler" -}}
    {{- if semverCompare ">=1.32.0" .version -}}v1.9.0-2
    {{- else if semverCompare ">=1.27.0" .version -}}v1.8.11-5
    {{- else if semverCompare ">=1.22.0" .version -}}v1.8.8
    {{- else if semverCompare ">=1.18.0" .version -}}1.8.3
    {{- else -}}1.7.1-hotfix.20200403
    {{- end -}}
  {{- else if eq .component "container-networking-cilium-agent" -}}
    {{- if semverCompare ">=1.31.0" .version -}}v1.16.6-250129
    {{- else if semverCompare ">=1.29.0" .version -}}v1.14.19-250129
    {{- else if semverCompare ">=1.27.0" .version -}}v1.13.18-241024
    {{- else -}}v1.14.19-250129
    {{- end -}}
  {{- else if eq .component "container-networking-cilium-operator-generic" -}}
    {{- if semverCompare ">=1.31.0" .version -}}v1.16.6-250129
    {{- else if semverCompare ">=1.29.0" .version -}}v1.14.19-250129
    {{- else if semverCompare ">=1.27.0" .version -}}v1.13.18-241024
    {{- else -}}v1.14.19-250129
    {{- end -}}
  {{- else if eq .component "coredns" -}}
    {{- if semverCompare ">=1.33.0" .version -}}v1.12.1-2
    {{- else if semverCompare ">=1.32.0" .version -}}v1.11.3-8
    {{- else if semverCompare ">=1.24.0" .version -}}v1.9.4-6
    {{- else if semverCompare ">=1.20.0" .version -}}v1.8.7
    {{- else -}}1.6.6
    {{- end -}}
  {{- else if eq .component "cost-analysis-agent" -}}
v0.0.24
  {{- else if eq .component "cost-analysis-opencost" -}}
v1.111.0
  {{- else if eq .component "cost-analysis-prometheus" -}}
v2.54.1
  {{- else if eq .component "cost-analysis-victoria-metrics" -}}
v1.103.0
  {{- else if eq .component "extension-config-agent" -}}
1.28.0
  {{- else if eq .component "extension-manager" -}}
1.28.0
  {{- else if eq .component "fqdn-policy" -}}
    {{- if semverCompare ">=1.31.0" .version -}}v1.16.6-250129
    {{- else -}}v1.14.19-250129
    {{- end -}}
  {{- else if eq .component "gpu-provisioner" -}}
0.3.5
  {{- else if eq .component "health-probe-proxy" -}}
v1.29.1
  {{- else if eq .component "hubble-relay" -}}
v1.15.0
  {{- else if eq .component "identity-binding-workload-identity-webhook" -}}
v1.6.0-alpha.1
  {{- else if eq .component "image-cleaner" -}}
v1.4.0-4
  {{- else if eq .component "ingress-appgw" -}}
    {{- if semverCompare ">=1.27.0" .version -}}1.8.1
    {{- else if semverCompare ">=1.19.0" .version -}}1.5.3
    {{- else -}}1.4.0
    {{- end -}}
  {{- else if eq .component "ip-masq-agent-v2" -}}
v0.1.15-2
  {{- else if eq .component "ipv6-hp-bpf" -}}
    {{- if semverCompare ">=1.29.0" .version -}}v0.0.1
    {{- else -}}v0.0.1
    {{- end -}}
  {{- else if eq .component "keda" -}}
    {{- if semverCompare ">=1.33.0" .version -}}2.17.1
    {{- else if semverCompare ">=1.32.0" .version -}}v2.16.1
    {{- else if semverCompare ">=1.30.0" .version -}}2.14.1
    {{- else if semverCompare ">=1.27.0" .version -}}2.11.2
    {{- else if semverCompare ">=1.26.0" .version -}}2.10.1
    {{- else if semverCompare ">=1.23.0" .version -}}2.9.3
    {{- else -}}2.8.1
    {{- end -}}
  {{- else if eq .component "keda-admission-webhooks" -}}
    {{- if semverCompare ">=1.33.0" .version -}}2.17.1
    {{- else if semverCompare ">=1.32.0" .version -}}v2.16.1
    {{- else if semverCompare ">=1.30.0" .version -}}2.14.1
    {{- else if semverCompare ">=1.27.0" .version -}}2.11.2
    {{- else -}}2.10.1
    {{- end -}}
  {{- else if eq .component "keda-metrics-apiserver" -}}
    {{- if semverCompare ">=1.33.0" .version -}}2.17.1
    {{- else if semverCompare ">=1.32.0" .version -}}v2.16.1
    {{- else if semverCompare ">=1.30.0" .version -}}2.14.1
    {{- else if semverCompare ">=1.27.0" .version -}}2.11.2
    {{- else if semverCompare ">=1.26.0" .version -}}2.10.1
    {{- else if semverCompare ">=1.23.0" .version -}}2.9.3
    {{- else -}}2.8.1
    {{- end -}}
  {{- else if eq .component "kube-egress-gateway-cni" -}}
    {{- if semverCompare ">=1.34.0" .version -}}v0.1.1
    {{- else -}}v0.0.21
    {{- end -}}
  {{- else if eq .component "kube-egress-gateway-cni-ipam" -}}
    {{- if semverCompare ">=1.34.0" .version -}}v0.1.1
    {{- else -}}v0.0.21
    {{- end -}}
  {{- else if eq .component "kube-egress-gateway-cnimanager" -}}
    {{- if semverCompare ">=1.34.0" .version -}}v0.1.1
    {{- else -}}v0.0.21
    {{- end -}}
  {{- else if eq .component "kube-egress-gateway-daemon" -}}
    {{- if semverCompare ">=1.34.0" .version -}}v0.1.1
    {{- else -}}v0.0.21
    {{- end -}}
  {{- else if eq .component "kube-egress-gateway-daemon-init" -}}
    {{- if semverCompare ">=1.34.0" .version -}}v0.1.1
    {{- else -}}v0.0.21
    {{- end -}}
  {{- else if eq .component "local-csi-driver" -}}
v0.2.4
  {{- else if eq .component "local-csi-driver-csi-provisioner" -}}
v5.2.0
  {{- else if eq .component "local-csi-driver-csi-resizer" -}}
v1.13.2
  {{- else if eq .component "local-csi-driver-registrar" -}}
v2.13.0
  {{- else if eq .component "metrics-server" -}}
    {{- if semverCompare ">=1.32.0" .version -}}v0.7.2-7
    {{- else if semverCompare ">=1.24.0" .version -}}v0.6.3-6
    {{- else if semverCompare ">=1.22.0" .version -}}v0.5.2
    {{- else if semverCompare ">=1.21.0" .version -}}v0.4.5
    {{- else if semverCompare ">=1.8.0" .version -}}v0.3.6
    {{- else -}}v0.2.1
    {{- end -}}
  {{- else if eq .component "microsoft-defender-admission-controller" -}}
20250706.3
  {{- else if eq .component "microsoft-defender-low-level-collector" -}}
    {{- if semverCompare ">=1.25.0" .version -}}2.0.221
    {{- else -}}1.3.81
    {{- end -}}
  {{- else if eq .component "microsoft-defender-low-level-init" -}}
1.3.81
  {{- else if eq .component "microsoft-defender-old-file-cleaner" -}}
1.0.273
  {{- else if eq .component "microsoft-defender-pod-collector" -}}
1.0.202
  {{- else if eq .component "microsoft-defender-security-publisher" -}}
1.0.273
  {{- else if eq .component "open-policy-agent-gatekeeper" -}}
    {{- if semverCompare ">=1.27.0" .version -}}v3.20.0-1
    {{- else if semverCompare ">=1.25.0" .version -}}v3.14.2
    {{- else if semverCompare ">=1.24.0" .version -}}v3.11.1
    {{- else if semverCompare ">=1.21.0" .version -}}v3.8.1
    {{- else if semverCompare ">=1.18.0" .version -}}v3.7.1
    {{- else -}}v3.4.1
    {{- end -}}
  {{- else if eq .component "osm-bootstrap" -}}
    {{- if semverCompare ">=1.24.0" .version -}}v1.2.9
    {{- else if semverCompare ">=1.23.5" .version -}}v1.1.3
    {{- else -}}v1.0.0
    {{- end -}}
  {{- else if eq .component "osm-controller" -}}
    {{- if semverCompare ">=1.24.0" .version -}}v1.2.9
    {{- else if semverCompare ">=1.23.5" .version -}}v1.1.3
    {{- else -}}v1.0.0
    {{- end -}}
  {{- else if eq .component "osm-crds" -}}
    {{- if semverCompare ">=1.24.0" .version -}}v1.2.9
    {{- else if semverCompare ">=1.23.5" .version -}}v1.1.3
    {{- else -}}v1.0.0
    {{- end -}}
  {{- else if eq .component "osm-healthcheck" -}}
    {{- if semverCompare ">=1.24.0" .version -}}v1.2.9
    {{- else if semverCompare ">=1.23.5" .version -}}v1.1.3
    {{- else -}}v1.1.0
    {{- end -}}
  {{- else if eq .component "osm-init" -}}
    {{- if semverCompare ">=1.24.0" .version -}}v1.2.9
    {{- else if semverCompare ">=1.23.5" .version -}}v1.1.3
    {{- else -}}v1.0.0
    {{- end -}}
  {{- else if eq .component "osm-injector" -}}
    {{- if semverCompare ">=1.24.0" .version -}}v1.2.9
    {{- else if semverCompare ">=1.23.5" .version -}}v1.1.3
    {{- else -}}v1.0.0
    {{- end -}}
  {{- else if eq .component "osm-sidecar" -}}
    {{- if semverCompare ">=1.25.0" .version -}}v1.32.2-hotfix.20241216
    {{- else if semverCompare ">=1.24.0" .version -}}v1.25.9-hotfix.20231002
    {{- else -}}v1.19.1
    {{- end -}}
  {{- else if eq .component "overlay-vpa" -}}
    {{- if semverCompare ">=1.31.0" .version -}}v1.2.1-1
    {{- else if semverCompare ">=1.27.0" .version -}}v1.0.0-1
    {{- else if semverCompare ">=1.25.0" .version -}}0.13.0
    {{- else -}}0.11.0
    {{- end -}}
  {{- else if eq .component "overlay-vpa-webhook-generation" -}}
master.250827.1
  {{- else if eq .component "ratify-base" -}}
v1.2.3
  {{- else if eq .component "retina-agent" -}}
v1.0.0-rc2
  {{- else if eq .component "retina-agent-enterprise" -}}
v0.1.11
  {{- else if eq .component "retina-agent-win" -}}
v1.0.0-rc2
  {{- else if eq .component "retina-operator" -}}
v0.1.11
  {{- else if eq .component "secrets-store-csi-driver" -}}
    {{- if semverCompare ">=1.26.0" .version -}}v1.5.3
    {{- else if semverCompare ">=1.24.0" .version -}}v1.3.4-1
    {{- else -}}v1.3.0.3
    {{- end -}}
  {{- else if eq .component "secrets-store-csi-driver-windows" -}}
    {{- if semverCompare ">=1.26.0" .version -}}v1.5.3
    {{- else if semverCompare ">=1.24.0" .version -}}v1.3.4
    {{- else -}}v1.3.0
    {{- end -}}
  {{- else if eq .component "secrets-store-driver-registrar-linux" -}}
    {{- if semverCompare ">=1.26.0" .version -}}v2.13.0
    {{- else if semverCompare ">=1.24.0" .version -}}v2.8.0
    {{- else -}}v2.6.2
    {{- end -}}
  {{- else if eq .component "secrets-store-driver-registrar-windows" -}}
    {{- if semverCompare ">=1.26.0" .version -}}v2.13.0
    {{- else if semverCompare ">=1.24.0" .version -}}v2.8.0
    {{- else -}}v2.6.2
    {{- end -}}
  {{- else if eq .component "secrets-store-livenessprobe-linux" -}}
    {{- if semverCompare ">=1.26.0" .version -}}v2.15.0
    {{- else if semverCompare ">=1.24.0" .version -}}v2.10.0
    {{- else -}}v2.8.0
    {{- end -}}
  {{- else if eq .component "secrets-store-livenessprobe-windows" -}}
    {{- if semverCompare ">=1.26.0" .version -}}v2.15.0
    {{- else if semverCompare ">=1.24.0" .version -}}v2.10.0
    {{- else -}}v2.8.0
    {{- end -}}
  {{- else if eq .component "secrets-store-provider-azure" -}}
    {{- if semverCompare ">=1.26.0" .version -}}v1.7.0
    {{- else if semverCompare ">=1.24.0" .version -}}v1.4.1
    {{- else -}}v1.4.0
    {{- end -}}
  {{- else if eq .component "secrets-store-provider-azure-windows" -}}
    {{- if semverCompare ">=1.26.0" .version -}}v1.7.0
    {{- else if semverCompare ">=1.24.0" .version -}}v1.4.1
    {{- else -}}v1.4.0
    {{- end -}}
  {{- else if eq .component "sgx-attestation" -}}
3.3.1
  {{- else if eq .component "sgx-plugin" -}}
1.0.0
  {{- else if eq .component "sgx-webhook" -}}
1.2.2
  {{- else if eq .component "tigera-operator" -}}
    {{- if semverCompare ">=1.33.0" .version -}}v1.38.3
    {{- else if semverCompare ">=1.32.0" .version -}}v1.36.11
    {{- else if semverCompare ">=1.30.0" .version -}}v1.34.13
    {{- else if semverCompare ">=1.29.0" .version -}}v1.30.11
    {{- else if semverCompare ">=1.24.0" .version -}}v1.28.13
    {{- else -}}v1.23.8
    {{- end -}}
  {{- else if eq .component "windows-gmsa-webhook-image" -}}
v0.12.1-2
  {{- else if eq .component "workload-identity-webhook" -}}
v1.5.1
  {{- end -}}
{{- end -}}

{{/* Auto-generated by servicemesh tooling, do not edit. See /toolkit/servicemesh/README.md for more information. */}}
{{- define "get.istioImageTag" -}}
  {{- if eq .component "azure-service-mesh-istio" -}}
    {{- if eq "asm-1-27" .revision -}}1.27.0-1
    {{- else if eq "asm-1-26" .revision -}}1.26.3-2
    {{- else if eq "asm-1-25" .revision -}}1.25.3-4
    {{- else if eq "asm-1-24" .revision -}}1.24.6
    {{- else if eq "asm-1-23" .revision -}}1.23.6-hotfix.20250515
    {{- else if eq "asm-1-22" .revision -}}1.22.7
    {{- else if eq "asm-1-21" .revision -}}1.21.6
    {{- else if eq "asm-1-20" .revision -}}1.20.8
    {{- else if eq "asm-1-19" .revision -}}1.19.10-hotfix.20240528
    {{- else if eq "asm-1-18" .revision -}}1.18.7-hotfix.20240210
    {{- else if eq "asm-1-17" .revision -}}1.17.8
    {{- else -}}not-in-use-9.99.9
    {{- end -}}
  {{- end -}}
{{- end -}}
