{{- $settings := include "arc-extension-settings" . | fromYaml }}
#
# Workspace Secret
# Stores Log Analytics workspace credentials
#
apiVersion: v1
kind: Secret
metadata:
  name: ama-logs-secret
  namespace: kube-system
  labels:
{{- if $settings.legacyAddonDelivery }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
type: Opaque
data:
  WSID: {{ $settings.workspaceID | b64enc | quote }}
  KEY: {{ $settings.workspaceKey | b64enc | quote }}
  DOMAIN: {{ $settings.domain | b64enc | quote }}
{{- if $settings.isProxyEnabled }}
  {{- if $settings.httpsProxy }}
  PROXY: {{ $settings.httpsProxy | b64enc | quote }}
  {{- else if $settings.httpProxy }}
  PROXY: {{ $settings.httpProxy | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if and $settings.isProxyEnabled $settings.proxyCert }}
  PROXYCERT.crt: {{ $settings.proxyCert | quote }}
{{- end }}