{{- include (print $.Template.BasePath "/ensureExistsResources/_app-monitoring-webhook-mwhc.yaml") . }}
{{ $secret := lookup "v1" "Secret" "kube-system" "app-monitoring-webhook-cert" }}
{{ if or (not $secret) (not $secret.metadata) }}
{{- include (print $.Template.BasePath "/ensureExistsResources/_app-monitoring-secrets.yaml") . }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: app-monitoring-webhook-cert
  namespace: kube-system
data:
{{- $secret.data | toYaml | nindent 2 }}

{{ end }}