{{- if eq (.Values.genevaLogsConfig.authidType | lower) "authworkloadidentity" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
     azure.workload.identity/client-id: {{ trimPrefix "client_id#" .Values.genevaLogsConfig.authid | quote }}
  name: {{ .Values.genevaLogsConfig.serviceAccountName | quote}}
{{- end }}
