apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appmonitoringconfigs.azmon.app.monitoring # name must match the spec fields below, and be in the form: <plural>.<group>
spec:
  group: azmon.app.monitoring # group name to use for REST API: /apis/<group>/<version>
  names:
    plural: appmonitoringconfigs # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    singular: appmonitoringconfig # singular name to be used as an alias on the CLI and for display
    kind: appmonitoringconfig # kind is normally the CamelCased singular type. Your resource manifests use this.
    shortNames: # shortNames allow shorter string to match your resource on the CLI
    - appmonitoring
  scope: Namespaced # either Namespaced or Cluster
  versions:
    - name: v1
      served: true # Each version can be enabled/disabled by Served flag.
      storage: true # One and only one version must be marked as the storage version.
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                autoInstrumentationPlatforms:
                  type: array
                  default: [ DotNet, Java, NodeJs, OpenTelemetry ]
                  nullable: false
                  minItems: 0
                  maxItems: 4
                  items:
                    type: string
                    enum:
                    - DotNet
                    - Java
                    - NodeJs
                    - OpenTelemetry
                aiConnectionString:
                  type: string
                  nullable: false
                deployments:
                  type: array
                  default: []
                  nullable: false
                  items:
                    type: string
              required: [ aiConnectionString ]
          required: [ spec ]
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-monitoring-webhook-sa
  namespace: kube-system
  labels:
    component: app-monitoring-webhook-sa
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appmonitoringconfig-crd-watcher
rules:
- apiGroups: ["azmon.app.monitoring"]
  resources: ["appmonitoringconfigs"]
  verbs: ["get", "watch", "list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-monitoring-webhook-binding
subjects:
- kind: ServiceAccount
  name: app-monitoring-webhook-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: appmonitoringconfig-crd-watcher
  apiGroup: rbac.authorization.k8s.io
---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: app-monitoring-webhook-cert
#   namespace: default
# data:
#   ca.cert: Y2FDZXJ0
#   tls.cert: dGxzQ2VydA==
#   tls.key: dGxzS2V5
# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-monitoring-webhook-deployment
  namespace: kube-system
  labels:
    app: app-monitoring-webhook-deployment
spec:
  selector:
    matchLabels:
      app: app-monitoring-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: app-monitoring-webhook
    spec:
      containers:
        - name: app-monitoring-webhook
          image: aicommon.azurecr.io/aidev:v1
          imagePullPolicy: Always # IfNotPresent
          env: 
            - name: ARM_ID
              value: "/subscriptions/66010356-d8a5-42d3-8593-6aaa3aeb1c11/resourceGroups/rambhatt-rnd-v2/providers/Microsoft.ContainerService/managedClusters/aks-final"
            - name: ARM_REGION
              value: "westeastafricasouthblah"
          ports:
            - containerPort: 1337
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /mnt/webhook
              readOnly: true
      serviceAccount: app-monitoring-webhook-sa
      volumes:
        - name: webhook-certs
          secret:
            secretName: app-monitoring-webhook-cert
---

apiVersion: v1
kind: Service
metadata:
  name: app-monitoring-webhook-service
  namespace: kube-system
spec:
  # type: LoadBalancer
  ports:
    - port: 443
      protocol: TCP
      targetPort: 1337
  selector:
    app: app-monitoring-webhook
---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: app-monitoring-webhook
webhooks:
  - name: app-monitoring-webhook-service.kube-system.svc
    clientConfig:
      service:
        name: app-monitoring-webhook-service
        namespace: kube-system
        path: "/"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2VENDQXRHZ0F3SUJBZ0lSQVBQM0czSktMTjZTL1d4QkFDRnFlQ0V3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdJQmNOTWpNd05qQTJNRGd4TWpJMFdoZ1BNakExTXpBMk1EWXdPREl5TWpSYQpNQTB4Q3pBSkJnTlZCQU1UQW1OaE1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBCnpUTU9RdmVWblpHZkd2emlsZlNzK2lZNVpMcG1TenI4VTZXUkhEVzE1a2hsYVdUcitEMlRuZFJxbk1YVHVuQWMKQTlVWjN5cGxTMEsyb1RYQmQvR0xIQlNHZUtxVWJzNFVHVGNXRFR1Z1JHMno2cThYamZqMjBDR1ZjRytZYjJ3UQplV0xzSEJKSnJWL3NuS21KRE9UWG9BMDZrNDM3Z2lQVUZyTnYwRG1nOUdiRnE1U0gyb1B1S2h1aXR4cENKWEowCjZUSkxTWlNYNVlxMk11ZXhJeWpEaDJVRzRsSmdUWjBSa2wrbmZ5UVpuYkF4Vk1SbktrY2tXa2FSamJJSmxJbHkKckhWeGFyT21tYXNCOWNVZi92UkpQU2VIb1FLK3hBQTlUeU1EZlVKVGNUTGQyOEV3aS9qRkM5VnN1VVNJQ0o0dgpOMC9TOEw0Tm1seUd2dkVVM1NDdENCT3RkUDc1blJjeVlPaTFuVGlnTUdlSFpyait0aHNZK0xCSDVnektXOVcrClZUeml0N1MxMTdZeHRlUEJEaDRRay9KZVgrQTVNQnNGZXZtSVl3a3E5ejlQQVQ0N0FkR1cyWlVrcjc4UzJuOU8KSVlmOTFUZHpManZsaGdwK29vV2RqaE96NjBVMUoydnFOeU1YVUF0bnBjSFdJaUhNcHJoRE0wb0pzYktoL0RkbAo4dEJ2T082OEt6eTB4R3RCTmZhTjZjeElTVk5pU2ZUSngxVzQ0TUdmZ05EZ2NUTDduc2gxK1ZYWS9LcXozY0Q5CjVNV2ZaOHBxMk9hWklDZ3Y4aURrUkNTdHUvRExCWnBra3ZDOUR3YTBKSkl3Mm5zYlFLNUV6RXlZanBLYmFNYW0KS0Q1cWlGTkpjZ3B4My9Rb2xFYmhmSGtWNFVjTG1JOXhzRGFPK1hVK2U3c0NBd0VBQWFOQ01FQXdEZ1lEVlIwUApBUUgvQkFRREFnS2tNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGUDAwdHhKczMweldpKytyCjlFVVYybzhmU1Q1SE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQXk3U1o4KzJnQTRVMGlJUWpCR1lrZGpZbEcKMGpMS0hBK2liR01UOStSbVd5Zmx3WGxBT3JCQUx2NjFUOUJSQWhOZG8waENKK2hNcDN2a04zRTBrT2ZzcWNuTApJMUFKUGRBTVV4NktJMm9ZUUdsbWc2SnNMVlMybVF3TjFhWU9oMlNxUjJCN0JuZmVrakp2UjRZNGplcWVkK0pWCnJ6aHBtcituZXFCK1p3SXA1cnhGS1RhRHBPdWg4c0V1b3VjdGlpYk9NcDFyNUExUnZZLzFISmZRdjNzd25kRFgKVTFIQWRzUHJ1QndUcG1vZWM0UUpLWVFRQndtbENyT3Q2S1VXaitwZDRRYnVEM0diSjhyR2NMQVJQcDJ2VkU0OQpsakw0aW1jNE5YdDNIZTFoZmxHMjA2VUhMSTlCcHFCQ0RTWVg5ZUw2RGNPbXlMNk9vMjJRMThINHl1dTJ3eW9TCjc0NFJhUjl6am5PbDZOS0E1QTNLYUtoVWR5WDJFVjhGMkJlYnNURVBKWmI0M3dmOGxzVndHWlNYZS8zQWRXKy8KNXd3TGUwSWlGU2hDSVBIMU1TR1lGYnlWNXgxQmI4cVYxZVo4bTNIN2w0OWNXNnVGa21HaFRaMmVHemdXTDJlMwplVlpadkRVeThVdFo1bGVwaGUxNk4rKzA2L1lCeDcwWHRDOFFWTkhwWXFQOThYa1FuTW9BSitWMXV5NW9QbTQ5CkZmWU9RN3JUQW42S2crbVNUdXdMSkhhK0RCTWp2OUthT1hBQ3lWV2hTRnZwOVRLZEZsYWVBRDZJbXNyS2ZYZVMKeHRSbkIzeXlJb0hQWFV2ckR4K1BOSzZqKzZhNUZOOTdtZU1KNlpqT0JXR2JCY3JCVHplamozbFRWQ0hvbFl0dgpCQ0ozSmozL0hZbGswYXJuU1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"] 
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1"]
    # namespaceSelector:
    #   matchExpressions:
    #     - key: runlevel
    #       operator: NotIn
    #       values: ["0","1"]
---