apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instrumentations.monitor.azure.com # name must match the spec fields below, and be in the form: <plural>.<group>
spec:
  group: monitor.azure.com # group name to use for REST API: /apis/<group>/<version>
  names:
    plural: instrumentations # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    singular: instrumentation # singular name to be used as an alias on the CLI and for display
    kind: Instrumentation # kind is normally the PascalCase singular type. Your resource manifests use this.
  scope: Namespaced # either Namespaced or Cluster
  versions:
    - name: v1
      served: true # each version can be enabled/disabled. Defines whether k8s will serve this version to clients if asked to.
      storage: true # one and only one version must be marked as the storage version. This is how all CRs will be stored internally when crated.
      schema:
        openAPIV3Schema:
          description: >-
            Configures application monitoring in the current namespace. Multiple CRs of this kind are allowed within a namespace. 
            
            CR named _default_ will be used for every workload in the namespace unless speicifically overridden through annotations.
            To use a different CR _crName_ for a particular workload, mark it with _instrumentation.opentelemetry.io/inject-\<language\>="\<crName\>"_ annotation.

            Multiple annotations (for different languages) may be applied to the same workload. Annotations must be placed at the workload's spec level (_spec.template.metadata.annotations_) level. Currently, only deployments are supported.
            
            Examples of annotation usage:

            instrumentation.opentelemetry.io/inject-java="true"
            Uses the default CR for the namespace with Java instrumentation (regardless of which languages the default CR specifies)

            instrumentation.opentelemetry.io/inject-java="false"
            Disables all instrumentation regardless of which languages the default CR specifies, or which language-specific annotation is used.

            instrumentation.opentelemetry.io/inject-java="true"
            instrumentation.opentelemetry.io/inject-dotnet="true"
            Uses the default CR for the namespace with Java and .NET instrumentation (regardless of which languages the default CR specifies)

            instrumentation.opentelemetry.io/inject-java="true"
            instrumentation.opentelemetry.io/inject-dotnet="false"
            Uses the default CR for the namespace with Java (regardless of which languages the default CR specifies)

            instrumentation.opentelemetry.io/inject-java="alternativeCrInThisNamespace"
            Uses a different, non-default CR named _alternativeCrInThisNamespace_ found within the namespace with Java instrumentation (regardless of which languages that CR specifies)

            instrumentation.opentelemetry.io/inject-java="crName1"
            instrumentation.opentelemetry.io/inject-dotnet="crName2"
            Invalid configuration, deployment will fail.

            instrumentation.opentelemetry.io/inject-dotnet="crThatDoesNotExist"
            Invalid configuration since the CR does not exist, deployment will continue with no instrumentation.
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required: 
                - settings
                - destination
              properties:
                settings:
                  description: Determines which settings to apply as part of this configuration.
                  type: object
                  required:
                    - autoInstrumentationPlatforms
                  properties:
                    imageRepoPath:
                      description: "Path to a repository to fetch auto-instrumentation images from. Only use if you have an Artifact Cache set up to host related images normally found on Microsoft Container Registry (MCR). See here for details: https://learn.microsoft.com/en-us/azure/container-registry/tutorial-artifact-cache"
                      type: string
                    autoInstrumentationPlatforms:
                      description: List of auto-instrumentation platforms to use (must match the type of the application running in the container). Can be empty to use none. Ignored for named (non-default) CRs.
                      type: array
                      minItems: 0
                      items:
                        type: string
                        enum:
                          - DotNet
                          - Java
                          - NodeJs
                    logCollectionSettings:
                      description: >-
                        Before this configuration is applied, Azure Monitor already collects pod console output and uploads it to ConsoleLog / ConsoleLogV2 tables in the associated Log Analytics Workspace by Azure Monitor Container Insights.
                        Logs that were output via the console lose distributed tracing context and cannot be visualized in the end-to-end transaction details experience.
                        The following flags allow for configuring what works best for a particular monitoring scenario.
                      type: object
                      properties:
                        disableAppLogs:
                          description: >-
                            Controls whether logs produced by standard logging framework are uploaded to Application Insights.
                            Different languages may support different logging frameworks, and support will change over time.
                            Note: enabling this flag without disabling console output (either through the flag in this setion or by removing the console adapters when configuring the SDK) might result in double collection of logs and higher cost.
                          type: boolean
                          default: false
                  
                destination:
                  description: Sink for telemetry data
                  type: object
                  required:
                    - applicationInsightsConnectionString
                  properties:
                    applicationInsightsConnectionString:
                      description: Connection string of the Application Insights component to send telemetry data to.
                      type: string
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-monitoring-webhook-sa
  namespace: kube-system
  labels:
    component: app-monitoring-webhook-sa
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instrumentation-crd-watcher
rules:
- apiGroups: ["monitor.azure.com"]
  resources: ["instrumentations"]
  verbs: ["get", "watch", "list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-monitoring-webhook-binding
subjects:
- kind: ServiceAccount
  name: app-monitoring-webhook-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: instrumentation-crd-watcher
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: v1
kind: Secret
metadata:
  name: app-monitoring-webhook-cert
  namespace: kube-system
data:
  ca.cert: Y2FDZXJ0
  tls.cert: dGxzQ2VydA==
  tls.key: dGxzS2V5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-monitoring-webhook
  namespace: kube-system
  labels:
    app: app-monitoring-webhook
spec:
  selector:
    matchLabels:
      app: app-monitoring-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: app-monitoring-webhook
    spec:
      containers:
        - name: app-monitoring-webhook
          image: aicommon.azurecr.io/aidev:v1
          imagePullPolicy: Always # IfNotPresent
          env: 
            - name: ARM_ID
              value: "/subscriptions/5a3b3ba4-3a42-42ae-b2cb-f882345803bc/resourcegroups/alkaplan-rg/providers/Microsoft.ContainerService/managedClusters/alkaplan-aks"
            - name: ARM_REGION
              value: "eastus"
          ports:
            - containerPort: 1337
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /mnt/webhook
              readOnly: true
      serviceAccount: app-monitoring-webhook-sa
      volumes:
        - name: webhook-certs
          secret:
            secretName: app-monitoring-webhook-cert
---

apiVersion: v1
kind: Service
metadata:
  name: app-monitoring-webhook-service
  namespace: kube-system
spec:
  # type: LoadBalancer
  ports:
    - port: 443
      protocol: TCP
      targetPort: 1337
  selector:
    app: app-monitoring-webhook
---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: app-monitoring-webhook
webhooks:
  - name: app-monitoring-webhook-service.kube-system.svc
    clientConfig:
      service:
        name: app-monitoring-webhook-service
        namespace: kube-system
        path: "/"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2VENDQXRHZ0F3SUJBZ0lSQVBQM0czSktMTjZTL1d4QkFDRnFlQ0V3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdJQmNOTWpNd05qQTJNRGd4TWpJMFdoZ1BNakExTXpBMk1EWXdPREl5TWpSYQpNQTB4Q3pBSkJnTlZCQU1UQW1OaE1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBCnpUTU9RdmVWblpHZkd2emlsZlNzK2lZNVpMcG1TenI4VTZXUkhEVzE1a2hsYVdUcitEMlRuZFJxbk1YVHVuQWMKQTlVWjN5cGxTMEsyb1RYQmQvR0xIQlNHZUtxVWJzNFVHVGNXRFR1Z1JHMno2cThYamZqMjBDR1ZjRytZYjJ3UQplV0xzSEJKSnJWL3NuS21KRE9UWG9BMDZrNDM3Z2lQVUZyTnYwRG1nOUdiRnE1U0gyb1B1S2h1aXR4cENKWEowCjZUSkxTWlNYNVlxMk11ZXhJeWpEaDJVRzRsSmdUWjBSa2wrbmZ5UVpuYkF4Vk1SbktrY2tXa2FSamJJSmxJbHkKckhWeGFyT21tYXNCOWNVZi92UkpQU2VIb1FLK3hBQTlUeU1EZlVKVGNUTGQyOEV3aS9qRkM5VnN1VVNJQ0o0dgpOMC9TOEw0Tm1seUd2dkVVM1NDdENCT3RkUDc1blJjeVlPaTFuVGlnTUdlSFpyait0aHNZK0xCSDVnektXOVcrClZUeml0N1MxMTdZeHRlUEJEaDRRay9KZVgrQTVNQnNGZXZtSVl3a3E5ejlQQVQ0N0FkR1cyWlVrcjc4UzJuOU8KSVlmOTFUZHpManZsaGdwK29vV2RqaE96NjBVMUoydnFOeU1YVUF0bnBjSFdJaUhNcHJoRE0wb0pzYktoL0RkbAo4dEJ2T082OEt6eTB4R3RCTmZhTjZjeElTVk5pU2ZUSngxVzQ0TUdmZ05EZ2NUTDduc2gxK1ZYWS9LcXozY0Q5CjVNV2ZaOHBxMk9hWklDZ3Y4aURrUkNTdHUvRExCWnBra3ZDOUR3YTBKSkl3Mm5zYlFLNUV6RXlZanBLYmFNYW0KS0Q1cWlGTkpjZ3B4My9Rb2xFYmhmSGtWNFVjTG1JOXhzRGFPK1hVK2U3c0NBd0VBQWFOQ01FQXdEZ1lEVlIwUApBUUgvQkFRREFnS2tNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGUDAwdHhKczMweldpKytyCjlFVVYybzhmU1Q1SE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQXk3U1o4KzJnQTRVMGlJUWpCR1lrZGpZbEcKMGpMS0hBK2liR01UOStSbVd5Zmx3WGxBT3JCQUx2NjFUOUJSQWhOZG8waENKK2hNcDN2a04zRTBrT2ZzcWNuTApJMUFKUGRBTVV4NktJMm9ZUUdsbWc2SnNMVlMybVF3TjFhWU9oMlNxUjJCN0JuZmVrakp2UjRZNGplcWVkK0pWCnJ6aHBtcituZXFCK1p3SXA1cnhGS1RhRHBPdWg4c0V1b3VjdGlpYk9NcDFyNUExUnZZLzFISmZRdjNzd25kRFgKVTFIQWRzUHJ1QndUcG1vZWM0UUpLWVFRQndtbENyT3Q2S1VXaitwZDRRYnVEM0diSjhyR2NMQVJQcDJ2VkU0OQpsakw0aW1jNE5YdDNIZTFoZmxHMjA2VUhMSTlCcHFCQ0RTWVg5ZUw2RGNPbXlMNk9vMjJRMThINHl1dTJ3eW9TCjc0NFJhUjl6am5PbDZOS0E1QTNLYUtoVWR5WDJFVjhGMkJlYnNURVBKWmI0M3dmOGxzVndHWlNYZS8zQWRXKy8KNXd3TGUwSWlGU2hDSVBIMU1TR1lGYnlWNXgxQmI4cVYxZVo4bTNIN2w0OWNXNnVGa21HaFRaMmVHemdXTDJlMwplVlpadkRVeThVdFo1bGVwaGUxNk4rKzA2L1lCeDcwWHRDOFFWTkhwWXFQOThYa1FuTW9BSitWMXV5NW9QbTQ5CkZmWU9RN3JUQW42S2crbVNUdXdMSkhhK0RCTWp2OUthT1hBQ3lWV2hTRnZwOVRLZEZsYWVBRDZJbXNyS2ZYZVMKeHRSbkIzeXlJb0hQWFV2ckR4K1BOSzZqKzZhNUZOOTdtZU1KNlpqT0JXR2JCY3JCVHplamozbFRWQ0hvbFl0dgpCQ0ozSmozL0hZbGswYXJuU1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["deployments"]
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1"]
    # namespaceSelector:
    #   matchExpressions:
    #     - key: runlevel
    #       operator: NotIn
    #       values: ["0","1"]
---