apiVersion: azmon.app.monitoring/v1
kind: appmonitoringconfig
metadata:
 name: appmonitoring
 namespace: default
spec:
 autoInstrumentationPlatforms: [ NodeJs ] #DotNet, Java, NodeJs ] # OpenTelemetry ]
 aiConnectionString: "InstrumentationKey=e368995c-b30a-4724-84d1-dac2cfef24b5;IngestionEndpoint=https://eastus2-3.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus2.livediagnostics.monitor.azure.com/"
 #deployments: [ deployment1, deployment2 ]
---