apiVersion: apps/v1
kind: Deployment
metadata:
  name:  customer-deployment-1
  namespace: default
  labels:
    app: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: aicommon.azurecr.io/aitestapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---