{
 "title": "Azure Monitor for Containers - Geneva Logs Multitenacy- Infra Namespaces",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fluent-bit input records/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_input_records_total{cluster=~\"$cluster\", name=~\"infra_*\"}[5m]))",
     "legendFormat": "All Nodes"
    }
   ]
  },
  {
   "title": "Fluent-bit output process records/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\", name=~\"infra_*\"}[5m]))",
     "legendFormat": "All Nodes"
    }
   ]
  },
  {
   "title": "Fluent-bit input records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_records_total{cluster=~\"$cluster\",name=~\"infra_*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output process records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\", name=~\"infra_*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output errors/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_errors_total{cluster=~\"$cluster\",name=~\"infra_*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output dropped records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_dropped_records_total{cluster=~\"$cluster\", name=~\"infra_*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input bytes/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_bytes_total{cluster=~\"$cluster\",name=~\"infra_*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output bytes/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_proc_bytes_total{cluster=~\"$cluster\",name=~\"infra_*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input records/s by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (name) (rate(fluentbit_input_records_total{cluster=~\"$cluster\", name=~\"infra_*\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output records/s by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 29 },
   "targets": [
    {
     "expr": "sum by (name) (rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\", name=~\"infra_*\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input files closed/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_files_closed_total{cluster=~\"$cluster\",name=~\"infra_*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit retries failed errors/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 36 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_retries_failed_total{cluster=~\"$cluster\",name=~\"infra_*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit rotated files/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_files_rotated_total{cluster=~\"$cluster\",name=~\"infra_*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input files opened/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 43 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_files_opened_total{cluster=~\"$cluster\",name=~\"infra_*\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}