apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
      annotations:
        instrumentation.opentelemetry.io/inject-configuration: "true"
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          env:
            - name: TARGET_URL
              value: "{{ .Values.targetUrl }}"
            - name: PORT
              value: "{{ .Values.port }}"
          ports:
            - containerPort: {{ .Values.port }}
