apiVersion: v1
kind: Secret
metadata:
  name: app-monitoring-webhook-cert
  namespace: kube-system
data:
  ca.cert: {{ "baseValue" | b64enc | quote }}
  tls.cert: {{ "baseValue" | b64enc | quote }}
  tls.key: {{ "baseValue" | b64enc | quote }}