apiVersion: v2
name: java-test-app
description: A Helm chart for Java test app
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/microsoft/Docker-Provider
sources:
  - https://github.com/microsoft/Docker-Provider
maintainers:
  - name: Microsoft
    email: containerinsights@microsoft.com
keywords:
  - monitoring
  - testing
  - java
annotations:
  category: Testing