# Default values for nodejs-test-app
appName: nodejs-test-app
image: appmonitoring.azurecr.io/demoaks-nodejs-app:latest

# Port the service runs on
port: 3001

# Target URL for the /call-target endpoint
targetUrl: "http://testappsource-service.default.svc.cluster.local:3001"

# Application Insights configuration for logging
appInsightsConfig: '{"logInstrumentationOptions":{"console":{"enabled":true},"bunyan":{"enabled":true},"winston":{"enabled":true}}}'