apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${JAVA_TEST_APP_NAME}
  namespace: ${TEST_NS}
  labels:
    app: java-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-test-app
  template:
    metadata:
      labels:
        app: java-test-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 3000
      containers:
      - name: java-test-app
        image: appmonitoring.azurecr.io/demoaks-java-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: TARGET_URL
          value: "http://${TEST_APP_SOURCE_NAME}-service.default.svc.cluster.local:3001"
---
apiVersion: v1
kind: Service
metadata:
  name: ${JAVA_TEST_APP_NAME}-service
  namespace: ${TEST_NS}
  labels:
    app: java-test-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: java-test-app