{
 "title": "Azure Monitor / Container Insights /QoS - Logs Multitenacy - Basic Mode",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"cadvisor\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Daemonset (all namespaces)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fluent-bit input  records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_records_total{cluster=~\"$cluster\", name!~\"ama-logs-*|mon-agent-*|telegraf-*|azmon_tenant_record_modifier|azmon_tenant_grep|fluentbit_metrics_input|storage_*|fluentbit_metrics_input|oms_output\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit dropped records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_dropped_records_total{cluster=~\"$cluster\", name=~\"oms_output\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output  records/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\",name!~\"ama-logs-*|mon-agent-*|telegraf-*|azmon_tenant_record_modifier|azmon_tenant_grep|fluentbit_metrics_input|storage_*|fluentbit_metrics_input\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input  bytes/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_input_bytes_total{cluster=~\"$cluster\", name!~\"ama-logs-*|mon-agent-*|telegraf-*|azmon_tenant_record_modifier|azmon_tenant_grep|fluentbit_metrics_input|storage_*|fluentbit_metrics_input|oms_output\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output  bytes/s by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_proc_bytes_total{cluster=~\"$cluster\",name!~\"ama-logs-*|mon-agent-*|telegraf-*|azmon_tenant_record_modifier|azmon_tenant_grep|fluentbit_metrics_input|storage_*|fluentbit_metrics_input\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input  records/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_input_records_total{cluster=~\"$cluster\", name!~\"ama-logs-*|mon-agent-*|telegraf-*|azmon_tenant_record_modifier|azmon_tenant_grep|fluentbit_metrics_input|storage_*|fluentbit_metrics_input|oms_output\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit dropped records/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by () (rate(fluentbit_output_dropped_records_total{cluster=~\"$cluster\", name=~\"oms_output\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output  records/s by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 17 },
   "targets": [
    {
     "expr": "sum by (node) (rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\",name!~\"ama-logs-*|mon-agent-*|telegraf-*|azmon_tenant_record_modifier|azmon_tenant_grep|fluentbit_metrics_input|storage_*|fluentbit_metrics_input\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit retries failed/sec by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "\r\nsum by (node) (rate(fluentbit_output_retries_failed_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output errors/sec by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "\r\nsum by (node) (rate(fluentbit_output_errors_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit retries failed/sec by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "\r\nsum by () (rate(fluentbit_output_retries_failed_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output errors/sec by All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 32 },
   "targets": [
    {
     "expr": "\r\nsum by () (rate(fluentbit_output_errors_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit rotated files/sec by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "\r\nsum by (node) (rate(fluentbit_input_files_rotated_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input opened files/sec by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 39 },
   "targets": [
    {
     "expr": "\r\nsum by (node) (rate(fluentbit_input_files_opened_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fluent-bit input closed files/sec by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "\r\nsum by (node) (rate(fluentbit_input_files_closed_total{cluster=~\"$cluster\", job=\"ama-logs-daemonset\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}