# Default values for testappsource
appName: testappsource
image: appmonitoring.azurecr.io/aks-validation-source-app:latest

# Port the service runs on
port: 3001

# Message returned by the HTTP endpoint
message: "Hello from testappsource Node.js app!"