# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - 'ai_prod'

pr:
  branches:
    include:
    - 'ai_prod'

variables:
  armServiceConnectionName: 'Appmonitoring_Validation_Pipeline'
  subscription: '5a3b3ba4-3a42-42ae-b2cb-f882345803bc'
  containerRegistry: 'aicommon' # this build pushes to aicommon.azurecr.io with an image that is used for testing in validation cluster, then pushes an image once tests pass. That image is latre picked up by the release pipeline and reuploaded to MCR
  repoImageName: '${{ variables.containerRegistry }}.azurecr.io/validated/azuremonitor/applicationinsights/aiprod'
  repoTestImageName: '${{ variables.containerRegistry }}.azurecr.io/dev/azuremonitor/applicationinsights/aiprod'
  javaTestAppImageName: 'aicommon.azurecr.io/demoaks-java-app:latest'
  javaTestAppName: 'test-app-java'
  nodeTestAppImageName: 'aicommon.azurecr.io/demoaks-nodejs-app:latest'
  nodeTestAppName: 'test-app-nodejs'
  testNamespace: 'test-ns'
  aiConnectionString: 'InstrumentationKey=2b453402-fcfb-408f-8495-c551f0e82f46;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/'
  aiResourceId: '/subscriptions/5a3b3ba4-3a42-42ae-b2cb-f882345803bc/resourceGroups/aks-appmonitoring-pipeline/providers/microsoft.insights/components/appmonitoring-pipeline-validation-ai'
  Codeql.Enabled: true
  Codeql.BuildIdentifier: 'linuxbuild'
  AKSResourceGroup: 'aks-appmonitoring-pipeline'
  AKSResourceName: 'appmonitoring-webhook-testbed'
  IS_PR: $[eq(variables['Build.Reason'], 'PullRequest')]

jobs:
- job: common
  variables:
    Codeql.SkipTaskAutoInjection: true
  pool:
    name: rambhatt-test-es-pool
  steps:
  - checkout: self
    fetchDepth: 0
    fetchTags: true
  - task: ComponentGovernanceComponentDetection@0
  ## dev builds are in format Major.Minor.Patch-CommitAheadCount-CommitId
  ## prod release are in format Major.Minor.Patch
  ## preview release are in format preview-Major.Minor.Patch
  - bash: |
      commit=$(git describe --tags)
      imageTag="$commit"
            
      echo "imageTag is $imageTag"
      
      echo "##vso[task.setvariable variable=imageTag;isOutput=true]$imageTag"
      
      cd $(Build.SourcesDirectory)/deployment/mergebranch-webhook-deployment/ServiceGroupRoot/Scripts
    name: setup

- job: build_linux
  
  timeoutInMinutes: 120
  dependsOn: common
  pool:
    name: rambhatt-test-es-pool
  variables:
    imageTag: $[ dependencies.common.outputs['setup.imageTag'] ]
    testImageTagSuffix: $(imageTag)-$(Build.BuildId)
    testImageName: ${{ variables.repoTestImageName }}:${{ variables.testImageTagSuffix }}
    fullImageName: ${{ variables.repoImageName }}:$(imageTag)
    # This is necessary because of: https://github.com/moby/moby/issues/37965
    DOCKER_BUILDKIT: 1

  steps:
  - task: CodeQL3000Init@0
  - task: AzureCLI@2
    displayName: "Ready Image and push to ACR"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        mkdir -p $(Build.ArtifactStagingDirectory)/linux
        echo "${{ variables.fullImageName }}" > $(Build.ArtifactStagingDirectory)/fullImageName.txt

        