# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#

trigger: none
pr: none

jobs:
- deployment: Testkube
  environment: container-insights
  timeoutInMinutes: 120
  displayName: "Monitoring-Model-Cluster-WCUS tests"
  pool:
    name: Azure-Pipelines-CI-Test-EO
  variables:
    skipComponentGovernanceDetection: true
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          persistCredentials: true

        - task: AzureCLI@1
          displayName: Get kubeconfig
          inputs:
            azureSubscription: 'ContainerInsights_Build_Subscription_CI'
            scriptLocation: 'inlineScript'
            inlineScript: 'az aks get-credentials -g monitoring-model-cluster-wcus -n Monitoring-Model-Cluster-WCUS'
          
        - bash: |
            ./install-and-execute-testkube.sh AzureClientId=$(MonitoringModelClusterWCUSClientId)
          workingDirectory: $(Build.SourcesDirectory)/test/testkube/
          displayName: "Install and execute testkube tests"

- deployment: Testkube
  environment: container-insights
  timeoutInMinutes: 120
  displayName: "Monitoring-Model-Cluster-WEU tests"
  pool:
    name: Azure-Pipelines-CI-Test-EO
  variables:
    skipComponentGovernanceDetection: true
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          persistCredentials: true

        - task: AzureCLI@1
          displayName: Get kubeconfig
          inputs:
            azureSubscription: 'ContainerInsights_Build_Subscription_CI'
            scriptLocation: 'inlineScript'
            inlineScript: 'az aks get-credentials -g Monitoring-Model-Cluster-WEU -n Monitoring-Model-Cluster-WEU'
          
        - bash: |
            ./install-and-execute-testkube.sh AzureClientId=$(MonitoringModelClusterWEUClientId)
          workingDirectory: $(Build.SourcesDirectory)/test/testkube/
          displayName: "Install and execute testkube tests"

- deployment: Testkube
  environment: container-insights
  timeoutInMinutes: 120
  displayName: "ci-logs-prod-aks-geneva-integration tests"
  pool:
    name: Azure-Pipelines-CI-Test-EO
  variables:
    skipComponentGovernanceDetection: true
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          persistCredentials: true

        - task: AzureCLI@1
          displayName: Get kubeconfig
          inputs:
            azureSubscription: 'ContainerInsights_Build_Subscription_CI'
            scriptLocation: 'inlineScript'
            inlineScript: 'az aks get-credentials -g ci-logs-prod-aks -n ci-logs-prod-aks-geneva-integration
          
        - bash: |
            ./install-and-execute-testkube.sh AzureClientId=$(AksGenevaIntegrationClientId)
          workingDirectory: $(Build.SourcesDirectory)/test/testkube/
          displayName: "Install and execute testkube tests"

- deployment: Testkube
  environment: container-insights
  timeoutInMinutes: 120
  displayName: "ci-logs-prod-aks-geneva-integration-multi-tenancy tests"
  pool:
    name: Azure-Pipelines-CI-Test-EO
  variables:
    skipComponentGovernanceDetection: true
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          persistCredentials: true

        - task: AzureCLI@1
          displayName: Get kubeconfig
          inputs:
            azureSubscription: 'ContainerInsights_Build_Subscription_CI'
            scriptLocation: 'inlineScript'
            inlineScript: 'az aks get-credentials -g ci-logs-prod-aks -n ci-logs-prod-aks-geneva-integration-multi-tenancy'
          
        - bash: |
            ./install-and-execute-testkube.sh AzureClientId=$(AksGenevaIntegrationMultiTenancyClientId)
          workingDirectory: $(Build.SourcesDirectory)/test/testkube/
          displayName: "Install and execute testkube tests"

- deployment: Testkube
  environment: container-insights
  timeoutInMinutes: 120
  displayName: "ci-logs-prod-aks-work-load-identity tests"
  pool:
    name: Azure-Pipelines-CI-Test-EO
  variables:
    skipComponentGovernanceDetection: true
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          persistCredentials: true

        - task: AzureCLI@1
          displayName: Get kubeconfig
          inputs:
            azureSubscription: 'ContainerInsights_Build_Subscription_CI'
            scriptLocation: 'inlineScript'
            inlineScript: 'az aks get-credentials -g ci-logs-prod-aks -n ci-logs-prod-aks-work-load-identity'
          
        - bash: |
            ./install-and-execute-testkube.sh AzureClientId=$(AksWorkLoadIdentityClientId)
          workingDirectory: $(Build.SourcesDirectory)/test/testkube/
          displayName: "Install and execute testkube tests"

- deployment: Testkube
  environment: container-insights
  timeoutInMinutes: 120
  displayName: "ci-logs-prod-wcus-fips tests"
  pool:
    name: Azure-Pipelines-CI-Test-EO
  variables:
    skipComponentGovernanceDetection: true
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          persistCredentials: true

        - task: AzureCLI@1
          displayName: Get kubeconfig
          inputs:
            azureSubscription: 'ContainerInsights_Build_Subscription_CI'
            scriptLocation: 'inlineScript'
            inlineScript: 'az aks get-credentials -g ci-logs-prod-aks -n ci-logs-prod-wcus-fips'
          
        - bash: |
            ./install-and-execute-testkube.sh AzureClientId=$(WcusFipsClientId)
          workingDirectory: $(Build.SourcesDirectory)/test/testkube/
          displayName: "Install and execute testkube tests"