# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - 'ai_prod'

pr:
  branches:
    include:
    - 'ai_prod'

variables:
  armServiceConnectionName: 'Appmonitoring_Validation_Pipeline'
  subscription: '5a3b3ba4-3a42-42ae-b2cb-f882345803bc'
  containerRegistry: 'appmonitoring' # this build pushes to aicommon.azurecr.io with an image that is used for testing in validation cluster, then pushes an image once tests pass. That image is latre picked up by the release pipeline and reuploaded to MCR
  repoImageName: '${{ variables.containerRegistry }}.azurecr.io/public/azuremonitor/applicationinsights/aidev'
  repoTestImageName: '${{ variables.containerRegistry }}.azurecr.io/test/azuremonitor/applicationinsights/aidev'
  javaTestAppImageName: '${{ variables.containerRegistry }}.azurecr.io/demoaks-java-app:latest'
  javaTestAppName: 'java-test-app'
  nodeTestAppImageName: '${{ variables.containerRegistry }}.azurecr.io/demoaks-nodejs-app:latest'
  nodeTestAppName: 'nodejs-test-app'
  testNamespace: 'test-ns'
  aiConnectionString: 'InstrumentationKey=2b453402-fcfb-408f-8495-c551f0e82f46;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/'
  aiResourceId: '/subscriptions/5a3b3ba4-3a42-42ae-b2cb-f882345803bc/resourceGroups/aks-appmonitoring-pipeline/providers/microsoft.insights/components/appmonitoring-pipeline-validation-ai'
  Codeql.Enabled: true
  Codeql.BuildIdentifier: 'linuxbuild'
  AKSResourceGroup: 'aks-appmonitoring-pipeline'
  AKSResourceName: 'appmonitoring-webhook-testbed'
  IS_PR: $[eq(variables['Build.Reason'], 'PullRequest')]

jobs:
- job: common
  variables:
    Codeql.SkipTaskAutoInjection: true
  pool:
    name: rambhatt-test-es-pool
  steps:
  - checkout: self
    fetchDepth: 0
    fetchTags: true
  - task: ComponentGovernanceComponentDetection@0
  ## dev builds are in format Major.Minor.Patch-CommitAheadCount-CommitId
  ## prod release are in format Major.Minor.Patch
  ## preview release are in format preview-Major.Minor.Patch
  - bash: |
      commit=$(git describe --tags --abbrev=0)
      imageTag="$commit"
            
      echo "imageTag is $imageTag"
      
      echo "##vso[task.setvariable variable=imageTag;isOutput=true]$imageTag"
      
      cd $(Build.SourcesDirectory)/deployment/mergebranch-webhook-deployment/ServiceGroupRoot/Scripts
    name: setup

- job: build_linux  
  
  timeoutInMinutes: 120
  dependsOn: common
  pool:
    name: rambhatt-test-es-pool
  variables:
    imageTag: $[ dependencies.common.outputs['setup.imageTag'] ]
    testImageTagSuffix: $(imageTag)-$(Build.BuildId)
    testImageName: ${{ variables.repoTestImageName }}:${{ variables.testImageTagSuffix }}
    fullImageName: ${{ variables.repoImageName }}:$(imageTag)-rc-$(Build.BuildId)
    # This is necessary because of: https://github.com/moby/moby/issues/37965
    DOCKER_BUILDKIT: 1

  steps:
  - task: CodeQL3000Init@0
  - task: AzureCLI@2
    displayName: "Ready Image and push to ACR"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        mkdir -p $(Build.ArtifactStagingDirectory)/linux
        echo "Setting the image name..."
        echo "${{ variables.fullImageName }}" > $(Build.ArtifactStagingDirectory)/linux/fullImageName.txt

        echo "Installing NPM..."
        sudo apt-get -y install npm

        echo "Switching the directory..."
        cd appmonitoring/ts/src
        pwd
        ls -a
        
        echo "Installing npm packages..."
        sudo npm i
        sudo npm ci

        #echo "Updating packages..."
        #npm update
        
        echo "Building the typescript project..."
        tsc --build --force
        
        if [ $? -ne 0 ]
        then
          echo "Build failed"
          exit 1
        fi

        echo "Build is done"

        echo "Running ESLint..."
        npx eslint .

        if [ $? -ne 0 ]
        then
          echo "ESLint failed"
          exit 1
        fi

        echo "ESLint is done"

        echo "Running Jest..."
        npm test

        if [ $? -ne 0 ]
        then
          echo "Jest failed"
          exit 1
        fi

        echo "Jest is done"

        echo "Pruning packages..."
        sudo npx modclean -r
        sudo npm prune --production
        echo "Pruning packages is done"
        
        pwd
        ls -a
        
        sudo apt-get update && sudo apt-get -y install qemu binfmt-support qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        docker buildx create --name testbuilder
        docker buildx use testbuilder

        az --version
        az account show
        az account set -s ${{ variables.subscription }}
        az acr login -n ${{ variables.containerRegistry }}

        # NOTE: Using the prometheus-collector team's cached buildx image since moby/buildkit:buildx-stable-1 getting throttled
        docker pull mcr.microsoft.com/azuremonitor/containerinsights/cidev/prometheus-collector/images:buildx-stable-1
        docker buildx create --name dockerbuilder --driver docker-container --driver-opt image=mcr.microsoft.com/azuremonitor/containerinsights/cidev/prometheus-collector/images:buildx-stable-1 --use
        docker buildx inspect --bootstrap

        echo "Build reason = $(Build.Reason)"

        echo $(testImageName)
        
        docker buildx build --platform linux/amd64,linux/arm64 --tag $(testImageName) -f ./Dockerfile --build-arg IMAGE_TAG="$(testImageName)" --metadata-file $(Build.ArtifactStagingDirectory)/linux/metadata.json --push --provenance=false .
        docker pull $(testImageName)

        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

        echo "Running trivy scan..."
        echo ".trivyignore file:"
        cat .trivyignore

        trivy image --ignore-unfixed --format json --no-progress --severity HIGH,CRITICAL,MEDIUM --exit-code 1 $(testImageName)

  - task: CodeQL3000Finalize@0
  - bash: |
        echo "##vso[task.setvariable variable=testImageName;isOutput=true]$(testImageName)"
        echo "##vso[task.setvariable variable=fullImageName;isOutput=true]$(fullImageName)"
        echo "##vso[task.setvariable variable=testImageTagSuffix;isOutput=true]$(testImageTagSuffix)"
    name: exportVars


- job: validate_webhook_image
  dependsOn: build_linux
  condition: and(succeeded(), eq(variables['IS_PR'], 'False'))
  pool:
    name: rambhatt-test-es-pool
  variables:
    testImageName:  $[ dependencies.build_linux.outputs['exportVars.testImageName'] ]
    fullImageName:  $[ dependencies.build_linux.outputs['exportVars.fullImageName'] ]
    testImageTagSuffix: $[ dependencies.build_linux.outputs['exportVars.testImageTagSuffix'] ]
    # This is necessary because of: https://github.com/moby/moby/issues/37965
    DOCKER_BUILDKIT: 1

  steps:
  - task: AzureCLI@2
    displayName: "Create deployment in AKS"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/scripts
        pwd
        az account set --subscription ${{ variables.subscription }}
        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }} 

        sudo chmod u+x ./clean-install-appmonitoring.sh
        sudo chmod u+x ./prepare-aks-rp-charts.sh

        echo "Preparing charts..."
        if ! ./prepare-aks-rp-charts.sh ../validation-helm/app-monitoring-addon/templates/app-monitoring-agent.yaml; then
          echo "Chart preparation failed"
          exit 1
        fi

        echo "Checking for charts..."
        if ! ./clean-install-appmonitoring.sh $(testImageTagSuffix); then
          echo "Chart installation failed"
          exit 1
        fi

  - task: AzureCLI@2
    displayName: "Validate charts deployed to AKS"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/scripts
        pwd
        az account set --subscription ${{ variables.subscription }}
        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }} 

        sudo chmod u+x ./validate-aks-charts.sh
        sudo chmod u+x ./validate-certs.sh

        echo "Waiting for 30 seconds for charts to be ready..."
        sleep 30

        echo "Checking for charts..."
        if ! ./validate-aks-charts.sh; then
          echo "Chart validation failed"
          exit 1
        fi

        echo "Checking for certificate installation..."
        if ! ./validate-certs.sh; then
          echo "Certificate validation failed"
          exit 1
        fi

  - task: AzureCLI@2
    displayName: "Install CR and test apps"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/validation-helm
        pwd
        az account set --subscription ${{ variables.subscription }}
        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }} 

        export JAVA_TEST_IMAGE_NAME=${{ variables.javaTestAppImageName }}
        export NODEJS_TEST_IMAGE_NAME=${{ variables.nodeTestAppImageName }}
        export JAVA_TEST_APP_NAME="${{ variables.javaTestAppName }}"
        export NODEJS_TEST_APP_NAME="${{ variables.nodeTestAppName }}"
        export TEST_APP_SOURCE_NAME="nodejs-source-app"
        export NODEJS_CALLER_APP_NAME="nodejs-caller-app"
        export TEST_NS="${{ variables.testNamespace }}"
        export AI_CONNECTION_STRING="${{ variables.aiConnectionString }}"

        sudo chmod +x ../scripts/install-test-apps.sh

        if ! ../scripts/install-test-apps.sh; then
          echo "Test apps installation failed"
          exit 1
        fi

  - task: AzureCLI@2
    displayName: "Check test apps were mutated correctly"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/scripts
        pwd
        az account set --subscription ${{ variables.subscription }}
        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }}
        
        sudo chmod u+x ./validate-mutation.sh

        if ! ./validate-mutation.sh ${{ variables.javaTestAppName }} ${{ variables.nodeTestAppName }} ${{ variables.testNamespace }}; then
          echo "Mutation validation failed"
          exit 1
        fi

  - task: AzureCLI@2
    displayName: "Check test apps are sending telemetry to AI"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/scripts
        pwd
        az account set --subscription ${{ variables.subscription }}
        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }} 
        export JAVA_TEST_APP_NAME="${{ variables.javaTestAppName }}"
        export NODEJS_TEST_APP_NAME="${{ variables.nodeTestAppName }}"

        echo "Wait for 3m for telemetry to flow..."
        sleep 180
        
        sudo chmod u+x ./validate_ai.sh

        if ! ./validate_ai.sh ${{ variables.aiResourceId }} ${{ variables.testNamespace }}; then
          echo "AI telemetry validation failed"
          exit 1
        fi

  - task: AzureCLI@2
    displayName: "Validate Housekeeper Cron Job"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/scripts
        pwd
        az account set --subscription ${{ variables.subscription }}
        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }} 

        sudo chmod u+x ./test-cronjob.sh
        sudo chmod u+x ./validate-certs.sh

        echo "Checking for charts..."
        if ! ./test-cronjob.sh; then
          echo "Cron Job validation failed"
          exit 1
        fi

  - task: AzureCLI@2
    displayName: "Restart webhook deployment"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/scripts
        pwd
        az account set --subscription ${{ variables.subscription }}
        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }} 

        kubectl rollout restart -n kube-system deployment/app-monitoring-webhook 

  - task: AzureCLI@2
    displayName: "Check test apps were mutated correctly"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/scripts
        pwd
        az account set --subscription ${{ variables.subscription }}
        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }}
        
        sudo chmod u+x ./validate-mutation.sh

        if ! ./validate-mutation.sh "${{ variables.javaTestAppName }}" "${{ variables.nodeTestAppName }}" "${{ variables.testNamespace }}"; then
          echo "Mutation validation failed"
          exit 1
        fi

  - task: AzureCLI@2
    displayName: "Check test apps are sending telemetry to AI"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd appmonitoring/scripts
        pwd
        az account set --subscription ${{ variables.subscription }}
        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }} 
        export JAVA_TEST_APP_NAME="${{ variables.javaTestAppName }}"
        export NODEJS_TEST_APP_NAME="${{ variables.nodeTestAppName }}"

        echo "Wait for 3m for telemetry to flow..."
        sleep 180
        
        sudo chmod u+x ./validate_ai.sh

        if ! ./validate_ai.sh ${{ variables.aiResourceId }} ${{ variables.testNamespace }}; then
          echo "AI telemetry validation failed"
          exit 1
        fi
        
  - task: AzureCLI@2
    displayName: "Retag the image as ready to deploy"
    inputs:
      azureSubscription: ${{ variables.armServiceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        az account show
        az account set -s ${{ variables.subscription }}

        # Login to prod ACR (destination) to push the image
        az acr login -n ${{ variables.containerRegistry }}
        docker pull $(testImageName)
        docker tag $(testImageName) $(fullImageName)
        docker push $(fullImageName)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop



