trigger: none
name: $(Date:yyyyMMdd).$(Rev:r)
variables:
- name: ACRName
  value: containerinsights.azurecr.io
- name: AgentImageTagSuffix
  value: ''
- name: AgentRelease
  value: ciprod
- name: AKSEngineCluster
  value: ciprod-rc-akse22-eus
- name: AKSEngineClusterKubeConfigSecretName
  value: ciprod-rc-akse22-eus-kubeconfig
- name: AKSScaleClusterKubeConfigSecretName
  value: ciscale-apr-2020-kubeconfig
- name: AKSScaleClusterRegion
  value: NorthCentralUS
- name: AKSScaleClusterResourceId
  value: /subscriptions/5a9b24b3-4658-4e41-b650-762cc0026438/resourcegroups/ciscale-apr-2020/providers/Microsoft.ContainerService/managedClusters/ciscale-apr-2020
- name: CDPXLinuxACR
  value: containerinsightsbuild
- name: CDPXLinuxRegistry
  value: /subscriptions/30c56c3a-54da-46ea-b004-06eb33432687/resourceGroups/ci-1es-build/providers/Microsoft.ContainerRegistry/registries/containerinsightsbuild
- name: CDPXLinuxRepoName
  value: linux
- name: CDPXLinuxTag
  value: cidev-20210923203527768-5e379473
- name: CDPXWindowsACR
  value: containerinsightsbuild
- name: CDPXWindowsRegistry
  value: /subscriptions/30c56c3a-54da-46ea-b004-06eb33432687/resourceGroups/ci-1es-build/providers/Microsoft.ContainerRegistry/registries/containerinsightsbuild
- name: CDPXWindowsRepoName
  value: windows
- name: CDPXWindowsTag
  value: win-cidev-20210923204137381-5e379473
- name: CIKV
  value: cdpxacrcredskv
- name: CIRelease
  value: ciprod
- name: ClusterRegion
  value: westeurope
- name: ClusterResourceId
  value: /subscriptions/9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb/resourceGroups/ciprod-rc-aks16-weu-rg/providers/Microsoft.ContainerService/managedClusters/ciprod-rc-aks16-weu
- name: ManagedIdentity
  value: /subscriptions/30c56c3a-54da-46ea-b004-06eb33432687/resourceGroups/containerinsightsprod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ev2-agent-release
- name: OverrideTag
  value: false
- name: ServiceTreeGuid
  value: 3170cdd2-19f0-4027-912b-1027311691a2
- name: UserAssignedIdentityClientId
  value: 332b8905-978c-453a-9014-d35e25a7a18a
- name: WorkspaceResourceId
  value: /subscriptions/9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb/resourcegroups/cimon-aks-wcus/providers/microsoft.operationalinsights/workspaces/cimon-aks-wcus
resources:
  pipelines:
  - pipeline: '_ContainerInsights-MultiArch-MergedBranches'
    project: 'microsoft'
    source: 'CDPX\docker-provider\ContainerInsights-MultiArch-MergedBranches'
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: 1ESPT-Pool-Name-Placeholder
      image: pool-image-placeholder
      os: windows
    serviceTreeId: 3170cdd2-19f0-4027-912b-1027311691a2
    customBuildTags:
    - ES365AIMigrationTooling-Release
    stages:
    - stage: Stage_1
      displayName: 'Note: Use Build with Telemetry Tag defined'
      trigger: manual
      jobs:
      - job: Job_1
        displayName: Agent job
        condition: succeeded()
        timeoutInMinutes: 0
        steps:
        - task: Bash@3
          displayName: Bash Script
          inputs:
            targetType: inline
            script: |
              echo 'Check that the build image you use has the telemetry tag defined'
    - stage: Stage_2
      displayName: Push Linux and Windows Agent
      dependsOn: []
      templateContext:
        cloud: Public
        isProduction: false
      jobs:
      - job: Job_2
        displayName: Agent job
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          type: releaseJob
          workflow: ev2-classic
          ev2:
            useServerMonitorTask: true
            serviceConnection: ci-ev2-ame
            serviceRootPath: build/mergebranch-multiarch-agent-deployment/ServiceGroupRoot
            rolloutSpecPath: RolloutSpecs.json
            inlineRolloutSpec: '{     "$schema": "https://ev2schema.azure.net/schemas/2020-01-01/rolloutSpecification.json",     "ContentVersion": "1.0.0.0",     "RolloutMetadata": {       "ServiceModelPath": "ServiceModels//Public.ServiceModel.json",          "ScopeBindingsPath": "ScopeBindings//Public.ScopeBindings.json",        "Name": "ContainerInsightsAgent",       "RolloutType": "Major",       "BuildSource": {         "Parameters": {           "VersionFile": "buildver.txt"         }       },       "Notification": {         "Email": {           "To": "sarahpeiffer@microsoft.com"         }       }       },     "OrchestratedSteps": [       {         "name": "PushLinuxAgent",         "targetType": "ServiceResource",         "targetName": "PushLinuxAgent",         "actions": [ "Shell/PushAgentToACR" ],         "dependsOn": [ ]       },       {         "name": "PushWindowsAgent",         "targetType": "ServiceResource",         "targetName": "PushWindowsAgent",         "actions": [ "Shell/PushAgentToACR" ],         "dependsOn": [ ]       }     ]   }'
            inlineScopeBindingOverrides: '{     "$schema": "https://ev2schema.azure.net/schemas/2020-01-01/scopeBindings.json",     "contentVersion": "0.0.0.1",     "scopeBindings": [                {             "scopeTagName": "Global",             "bindings": [                         {                     "find": "__ACR_NAME__",                     "replaceWith": "$(ACRName)"                 },                             {                     "find": "__AGENT_RELEASE__",                     "replaceWith": "$(AgentRelease)"                 },                  {                     "find": "__AGENT_IMAGE_TAG_SUFFIX__",                     "replaceWith": "$(AgentImageTagSuffix)"                 },                 {                     "find": "__MANAGED_IDENTITY__",                     "replaceWith": "$(ManagedIdentity)"                 },                  {                     "find": "__CDPX_LINUX_TAG__",                     "replaceWith": "$(CDPXLinuxTag)"                 },                 {                     "find": "__CDPX_WINDOWS_TAG__",                     "replaceWith": "$(CDPXWindowsTag)"                 },                 {                     "find": "__OVERRIDE_TAG__",                     "replaceWith": "$(OverrideTag)"                 }             ]         }                                                                                                                                                     ] }'
    - stage: Stage_3
      displayName: Deploy
      trigger: manual
      jobs:
      - job: Job_1
        displayName: Agent job
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          type: releaseJob
          isProduction: true
        steps:
        - task: AzureCLI@2
          displayName: Get Workspace ID and Key
          inputs:
            connectedServiceNameARM: ContainerInsights_Build_Subscription (9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)
            scriptType: bash
            scriptPath: $(System.DefaultWorkingDirectory)/_ContainerInsights-MultiArch-MergedBranches/drop/build/get-workspace-id-and-key.sh
            scriptArguments: WorkspaceResourceId=$(WorkspaceResourceId)
            cwd: $(System.DefaultWorkingDirectory)/_ContainerInsights-MultiArch-MergedBranches/drop/build
        - task: Bash@3
          displayName: Update Cluster ResourceId, Region, Image, WSID and WSKEY
          inputs:
            filePath: $(System.DefaultWorkingDirectory)/_ContainerInsights-MultiArch-MergedBranches/drop/build/update-place-holders-in-yaml.sh
            arguments: ClusterResourceId=$(ClusterResourceId) ClusterRegion=$(ClusterRegion) CIRelease=$(CIRelease) CIImageTagSuffix=$(AgentImageTagSuffix)
            workingDirectory: $(System.DefaultWorkingDirectory)/_ContainerInsights-MultiArch-MergedBranches/drop/build
        - task: Kubernetes@1
          displayName: kubectl apply
          inputs:
            connectionType: Azure Resource Manager
            azureSubscriptionEndpoint: ContainerInsights_Build_Subscription (9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)
            azureResourceGroup: ciprod-rc-aks16-weu-rg
            kubernetesCluster: ciprod-rc-aks16-weu
            useClusterAdmin: true
            namespace: kube-system
            command: apply
            arguments: -f ama-logs.yaml
            cwd: $(System.DefaultWorkingDirectory)/_ContainerInsights-MultiArch-MergedBranches/drop/build
        - task: HelmInstaller@0
          displayName: Install Helm 3.2.1
          inputs:
            helmVersion: 3.2.1
            checkLatestHelmVersion: false
        - task: AzureCLI@2
          displayName: Download Kubeconfig for AKS-Engine
          inputs:
            connectedServiceNameARM: ContainerInsights_Build_Subscription (9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)
            scriptType: bash
            scriptPath: $(System.DefaultWorkingDirectory)/_ContainerInsights-MultiArch-MergedBranches/drop/build/get-kube-config-from-kv.sh
            scriptArguments: KV=$(CIKV) KVSECRETNAMEKUBECONFIG=$(AKSEngineClusterKubeConfigSecretName)
        - task: Bash@3
          displayName: Install chart to aks-engine cluster
          inputs:
            filePath: $(System.DefaultWorkingDirectory)/_ContainerInsights-MultiArch-MergedBranches/drop/build/install-chart-to-aks-engine-cluster.sh
            arguments: ClusterName=$(AKSEngineCluster) CIRelease=$(CIRelease) CIImageTagSuffix=$(AgentImageTagSuffix)
            workingDirectory: $(System.DefaultWorkingDirectory)/_ContainerInsights-MultiArch-MergedBranches/drop/build
    - stage: Stage_4
      displayName: Deploy2ScaleCluster
      dependsOn: Stage_3
      jobs:
      - job: Job_1
        displayName: Agent job
        condition: succeeded()
        timeoutInMinutes: 0