FROM mcr.microsoft.com/azurelinux/base/core:3.0
ARG TARGETOS TARGETARCH
LABEL maintainer="OMSContainers@microsoft.com"
LABEL vendor=Microsoft\ Corp \
    com.microsoft.product="Azure Monitor for containers"

# Install basic utilities
RUN tdnf clean all
RUN tdnf repolist --refresh
RUN tdnf -y update
RUN tdnf install -y \
         build-essential \
        wget \
        curl \
        sudo \
        net-tools \
        cronie \
        rsyslog \
        dmidecode \
        gnupg \
        tar \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV tmpdir /opt
COPY kubernetes/linux/setup.sh kubernetes/linux/main.sh kubernetes/linux/defaultpromenvvariables kubernetes/linux/defaultpromenvvariables-rs kubernetes/linux/defaultpromenvvariables-sidecar kubernetes/linux/mdsd.xml kubernetes/linux/envmdsd kubernetes/linux/logrotate.conf $tmpdir/
COPY kubernetes/linux/azure-official-extras.repo /etc/yum.repos.d/

WORKDIR ${tmpdir}

RUN chmod 775 $tmpdir/*.sh; sync; $tmpdir/setup.sh 

# ENV APPLICATIONINSIGHTS_AUTH NzAwZGM5OGYtYTdhZC00NThkLWI5NWMtMjA3ZjM3NmM3YmRi
ENV MALLOC_ARENA_MAX 2
ENV HOST_MOUNT_PREFIX /hostfs
ENV HOST_PROC /hostfs/proc
ENV HOST_SYS /hostfs/sys
ENV HOST_ETC /hostfs/etc
ENV HOST_VAR /hostfs/var
ENV AZMON_COLLECT_ENV False
ENV KUBE_CLIENT_BACKOFF_BASE 1
ENV KUBE_CLIENT_BACKOFF_DURATION 0
# ENV RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR 0.9


ARG IMAGE_TAG=3.1.26
ENV AGENT_VERSION ${IMAGE_TAG}

# Default command
CMD ["fluentd", "-c", "/etc/fluentd/fluent25.conf"]
