FROM mcr.microsoft.com/azurelinux/base/core:3.0

# Set the platform to ensure we're building for Linux AMD64
ARG TARGETPLATFORM="linux/amd64"

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install basic utilities
RUN tdnf clean all
RUN tdnf repolist --refresh
RUN tdnf -y update
RUN tdnf install -y \
         build-essential \
        wget \
        curl \
        sudo \
        net-tools \
        cronie \
        rsyslog \
        dmidecode \
        gnupg \
        tar \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# RUN /usr/bin/apt-get update && /usr/bin/apt-get install -y --no-install-recommends \
#     curl \
#     ca-certificates \
#     gnupg2 \
#     apt-transport-https \
#     software-properties-common \
#     build-essential \
#     wget \
#     tar \
#     && /usr/bin/apt-get clean \
#     && rm -rf /var/lib/apt/lists/*

# Copy the fluentd setup script

COPY kubernetes/linux/setup.sh /usr/local/bin/setup.sh
RUN chmod +x /usr/local/bin/setup.sh

# Run the fluentd setup script
RUN /usr/local/bin/setup.sh

# Default command
CMD ["fluentd", "-c", "/etc/fluentd/fluent25.conf"]
