apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${NODEJS_TEST_APP_NAME}
  namespace: ${TEST_NS}
  labels:
    app: nodejs-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-test-app
  template:
    metadata:
      labels:
        app: nodejs-test-app
    spec:
      containers:
      - name: nodejs-test-app
        image: appmonitoring.azurecr.io/demoaks-nodejs-app:latest
        imagePullPolicy: Always
        env:
        - name: APPLICATIONINSIGHTS_CONFIGURATION_CONTENT
          value: '{"logInstrumentationOptions":{"console": { "enabled": true },"bunyan": { "enabled": true },"winston": { "enabled": true }}}'
        - name: TARGET_URL
          value: "http://${TEST_APP_SOURCE}-service.default.svc.cluster.local:3001"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: ${NODEJS_TEST_APP_NAME}-service
  namespace: ${TEST_NS}
  labels:
    app: nodejs-test-app
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: nodejs-test-app