name: Run Unit Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - ci_dev
      - ci_prod
  push:
    branches:
      - ci_dev
      - ci_prod
jobs:
  Golang-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.22.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          cd ${{ github.workspace }}
          ./test/unit-tests/run_go_tests.sh
  Ruby-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install fluent
        run: |
          sudo gem install fluentd -v "1.14.2" --no-document
          sudo gem install ipaddress --no-document
          sudo fluentd --setup ./fluent
      - name: Run unit tests
        run: |
          cd ${{ github.workspace }}
          ./test/unit-tests/run_ruby_tests.sh
